version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/survey_app:cached # sample_appとなっている場所は、好きなプロジェクト名に変更する
    command: sleep infinity # 開発コンテナが勝手にダウンしない為に設定する
    ports:
      - 3000:3000
